# @title Get information for a taxonomy ID
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX taxid: <http://identifiers.org/taxonomy/>

_:isAncestor(?ancestor, ?taxid) {
  ?taxid rdfs:subClassOf+ ?ancestor .
}

_:isCommonAncestor(?ancestor, ?taxid1, ?taxid2) {
  _:isAncestor(?ancestor, ?taxid1)
  _:isAncestor(?ancestor, ?taxid2)
}

SELECT DISTINCT ?ancestor ?label
WHERE {
  _:isCommonAncestor(?ancestor, taxid:9606, taxid:10090)
  ?ancestor rdfs:label ?label .
}
ORDER BY ?ancestor
