# @title Get information for a taxonomy ID
PREFIX taxid: <http://identifiers.org/taxonomy/>

SELECT ?taxid ?label
WHERE {
    ?taxid rdfs:label ?label
}
VALUES ?taxid { taxid:2 taxid:2157 taxid:2759 }
