# @title Get information for a taxonomy ID
PREFIX taxid: <http://identifiers.org/taxonomy/>

_:isAncestor(?ancestor, ?name) {
  ?human ?p ?name .
  ?human rdfs:subClassOf+ ?ancestor .
}  

SELECT ?ancestor ?label
WHERE {
  _:isAncestor(?ancestor, "human")
  ?ancestor rdfs:label ?label .
}
