#!/usr/bin/env spang2
# @endpoint orthodev
# @option -vac --time
# @param sign=Positive
# @param idref=affyProbeset
# @input ncbigene:20

SELECT ?tissue_40 ?tissue_10_ja ?tissue_10_en ?tissue_40_ja ?tissue_40_en (COUNT(DISTINCT ?gene) AS ?count)
WHERE {
  VALUES (?gene) { {{INUPT}} }
  ?gene refexo:{{idref}} ?seq .
  ?seq refexo:is{{sign}}lySpecificTo ?tissue_40 .
  ?tissue_40 skos:prefLabel ?tissue_40_en ;
      rdfs:label ?tissue_40_ja ;
      rdfs:subClassOf ?tissue_10 .
  ?tissue_10 skos:prefLabel ?tissue_10_en ;
      rdfs:label ?tissue_10_ja .
  FILTER(lang(?tissue_40_ja) = 'ja')
  FILTER(lang(?tissue_10_ja) = 'ja')
}
ORDER BY ?tissue_40
