#!/usr/bin/env spang2
# @title Count for each resource type
# @endpoint http://agrold.southgreen.fr/sparql
# @option -vac --time
PREFIX agrold: <http://www.southgreen.fr/agrold/vocabulary/>
PREFIX agrold_resource: <http://www.southgreen.fr/agrold/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX agro: <http://www.southgreen.fr/agrold/>

SELECT ?graph ?class ?so_label (COUNT(?s) AS ?count)
WHERE {
  VALUES ?class { agrold:Protein
                  agrold:Gene
                  agrold:mRNA
                  agrold:tRNA
                  agrold:Protein_Domain
                  agrold:nontranslating_CDS
                  agrold:snoRNA
                  agrold:lncRNA
                  agrold:lincRNA
                  agrold:ncRNA
                  agrold:rRNA
                  agrold:pre_miRNA
                  agrold:snRNA
                  agrold:pseudogene
                  agrold:miRNA
                  agrold:sense_intronic
                  agrold_resource:Gene
                  agrold:SRP_RNA
                  agrold:transposable_element
                  agrold:Chromosome
                  agrold:antisense_RNA
                  agrold:Transcription_Factor
                  agrold:RNase_MRP_RNA
                  agrold:Reaction
                  agrold:tRNA_pseudogene
                  agrold:Metabolic_Pathway
                  agrold_resource:QTL
                  agrold:ribozyme
                  obo:SO_0000147
                  obo:SO_0000234
                  obo:SO_0001217
                  obo:SO_0001263
                  obo:SO_0000253
                  obo:SO_0001877
                  obo:SO_0000275
                  obo:SO_0000655
                  obo:SO_0000252
                  obo:SO_0001244
                  obo:SO_0000274
                  obo:SO_0000336
                  obo:SO_0000516
                  obo:SO_0000276
                  obo:SO_0000101
                  obo:SO_0000590
                  obo:SO_0000111
                  obo:SO_0000385
                }
  GRAPH ?graph {
    ?s a ?class .
  }
  OPTIONAL {
    GRAPH agro:so {
      ?class rdfs:label ?so_label
    }
  }
}
ORDER BY ?graph DESC(?count)
