#!/usr/bin/env spang2
# @endpoint orthodev
# @option -vac --time
# @param sign=Positive
# @param idref=affyProbeset

SELECT DISTINCT ?gene ?tissue_40 ?tissue_10_ja ?tissue_10_en ?tissue_40_ja ?tissue_40_en
WHERE {
  ?gene refexo:{{idref}} ?seq .
  ?seq refexo:is{{sign}}lySpecificTo ?tissue_40 .
  ?tissue_40 skos:prefLabel ?tissue_40_en ;
      rdfs:label ?tissue_40_ja ;
      rdfs:subClassOf refexo:v01_10 .
  FILTER(lang(?tissue_40_ja) = 'ja')
}
ORDER BY ?gene ?tissue_40
