#!/usr/bin/env spang2
# @endpoint orthodev
# @option -ac --time
# @param sign=Positive
# @param idref=affyProbeset

SELECT DISTINCT ?gene
WHERE {
  ?gene refexo:{{idref}} ?seq .
  ?seq refexo:is{{sign}}lySpecificTo ?tissue_40 .
  ?tissue_40 skos:prefLabel ?tissue_40_en ;
}
