# @title Get genes associated with a specific disease, e.g. C0751955 ("Brain Infarction")
PREFIX umls: <http://linkedlifedata.com/resource/umls/id/>
SELECT DISTINCT ?gene ?score ?gene_label ?source
WHERE {
    ?gda sio:SIO_000253 ?source .
    ?dga sio:SIO_000216/sio:SIO_000300 ?score .
?dga sio:SIO_000628 ?gene, ?disease .
?gene a ncit:C16612 .
    ?gene rdfs:label ?gene_label .
}
ORDER BY DESC(?score) ?source
