#!/usr/bin/env spang2

# @title get children of a taxon with numbers of species
# @endpoint test
# @param taxid=40674

_:count(?taxon, ?count) {
  {
    SELECT (COUNT(DISTINCT ?species) AS ?count) ?taxon
    WHERE {
      ?species taxon:rank taxon:Species ;
          rdfs:subClassOf+ ?taxon .
    }
  }
}

SELECT ?order ?order_name ?count_order ?family ?family_name ?count_family ?species ?species_name
WHERE {
  ?species taxon:rank taxon:Species ;
      rdfs:label ?species_name ;
      rdfs:subClassOf+ taxid:{{taxid}} ;
      rdfs:subClassOf+ ?family ;
      rdfs:subClassOf+ ?order .
  ?family taxon:rank taxon:Family ;
      rdfs:label ?family_name .
  ?order taxon:rank taxon:Order ;
      rdfs:label ?order_name .
  _:count(?family, ?count_family)
  _:count(?order, ?count_order)
}
ORDER BY DESC(?count_order) ?order_name DESC(?count_family) ?family_name ?species_name
