PREFIX foo: <http://bar>
SELECT ?s     
where { ?s a
 foo:Human . # any human                                    
                                                                                                    
   }
